import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { CartProvider } from "@/lib/CartContext";
import { getCartItemCount } from "@/app/cart/actions";
import { cookies } from "next/headers";
import LayoutShell from "@/app/LayoutShell";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "My Store",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [cartItemCount, cookieStore] = await Promise.all([
    getCartItemCount(),
    cookies(),
  ]);
  const customerEmail = cookieStore.get("customer_email")?.value;

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <CartProvider initialCount={cartItemCount}>
          <LayoutShell customerEmail={customerEmail}>
            {children}
          </LayoutShell>
        </CartProvider>
      </body>
    </html>
  );
}
